services:
  - type: web
    name: crc-extractor-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.11.9
